# Generated by Django 6.0.6 on 2026-06-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilares',
            fields=[
                ('clave_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Clave ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del PILARES')),
                ('alcaldia', models.CharField(max_length=100, verbose_name='Alcaldía')),
                ('calle', models.CharField(blank=True, max_length=200, verbose_name='Calle')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('colonia', models.CharField(blank=True, max_length=200, verbose_name='Colonia')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitud')),
                ('pasta_termica', models.IntegerField(default=0, verbose_name='% Pasta térmica')),
                ('mouse_nuevos', models.IntegerField(default=0, verbose_name='Mouse nuevos')),
                ('teclados_nuevos', models.IntegerField(default=0, verbose_name='Teclados nuevos')),
                ('equipos_8gb', models.IntegerField(default=0, verbose_name='Equipos con 8GB RAM')),
                ('total_equipos', models.IntegerField(default=0, verbose_name='Total equipos')),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha último mantenimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PILARES',
                'verbose_name_plural': 'PILARES',
                'ordering': ['nombre'],
            },
        ),
    ]
