# Generated by Django 6.0.6 on 2026-06-12 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoNoFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100, verbose_name='Nombre/Modelo del equipo')),
                ('tipo_falla', models.CharField(choices=[('MOTHER', 'Placa Madre (Motherboard)'), ('VIDEO', 'Tarjeta de Video'), ('RAM', 'Memoria RAM'), ('DISCO', 'Disco Duro/SSD'), ('FUENTE', 'Fuente de Poder'), ('PANTALLA', 'Pantalla'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de falla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la falla')),
                ('mouse', models.BooleanField(default=False, verbose_name='Mouse no funcional')),
                ('teclado', models.BooleanField(default=False, verbose_name='Teclado no funcional')),
                ('monitor', models.BooleanField(default=False, verbose_name='Monitor no funcional')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('REPARADO', 'Reparado'), ('DESECHADO', 'Desechado'), ('EN_GARANTIA', 'En garantía')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_reporte', models.DateField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('fecha_solucion', models.DateField(blank=True, null=True, verbose_name='Fecha de solución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_no_funcionales', to='pilares.pilares')),
            ],
            options={
                'verbose_name': 'Equipo no funcional',
                'verbose_name_plural': 'Equipos no funcionales',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
