# Generated by Django 5.1.3 on 2026-06-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilares", "0002_equiponofuncional"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilares",
            name="modelo_equipo",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Modelo del equipo"
            ),
        ),
    ]
