# Generated by Django 6.0.6 on 2026-06-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilares', '0003_pilares_modelo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilares',
            name='equipos_inactivos',
            field=models.IntegerField(default=0, verbose_name='Equipos inactivos'),
        ),
    ]
