# Generated by Django 5.1.3 on 2026-06-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilares", "0003_pilares_modelo_equipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilares",
            name="equipos_inactivos",
            field=models.IntegerField(default=0, verbose_name="Equipos inactivos"),
        ),
    ]
