# Generated by Django 6.0.6 on 2026-06-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilares', '0004_pilares_equipos_inactivos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion_anterior', models.TextField(blank=True, verbose_name='Observación anterior')),
                ('observacion_nueva', models.TextField(blank=True, verbose_name='Observación nueva')),
                ('equipo_afectado', models.CharField(blank=True, max_length=100, verbose_name='Equipo afectado')),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('SOLUCION', 'Solución'), ('CIERRE', 'Cierre')], default='ACTUALIZACION', max_length=20, verbose_name='Tipo de cambio')),
                ('estado_anterior', models.CharField(blank=True, choices=[('ABIERTA', '🟡 Abierta'), ('EN_PROCESO', '🔵 En proceso'), ('SOLUCIONADA', '🟢 Solucionada'), ('CERRADA', '⚫ Cerrada')], max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, choices=[('ABIERTA', '🟡 Abierta'), ('EN_PROCESO', '🔵 En proceso'), ('SOLUCIONADA', '🟢 Solucionada'), ('CERRADA', '⚫ Cerrada')], max_length=20, verbose_name='Estado nuevo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('pilares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_observaciones', to='pilares.pilares')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de observación',
                'verbose_name_plural': 'Historial de observaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
